# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'DWUtilKitDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking'
  pod 'DTFoundation'
  pod 'JSONModel'
  pod 'SDWebImage'
  pod 'SDWebImage/MapKit'
  pod 'SDWebImage/GIF'
  pod 'SDWebImage/WebP'
#  pod 'KVOController'
  pod 'Masonry'
  pod 'AutoCoding'
  pod 'DZNEmptyDataSet'
  pod 'YTKNetwork'
  pod 'pop'
  pod 'IGListKit'
  pod 'YYModel'


  # Pods for DWUtilKitDemo

end
