platform :ios, ‘8.0’

target “DWUtilKitDemo” do
   pod 'AFNetworking'
   pod 'DTFoundation'
   pod 'JSONModel'
   pod 'SDWebImage'
   pod 'SDWebImage/MapKit'
   pod 'SDWebImage/GIF'
   pod 'SDWebImage/WebP'
   pod 'KVOController'
   pod 'Masonry'
   pod 'AutoCoding'
   pod 'DZNEmptyDataSet'
   pod 'YTKNetwork'
   pod 'pop'
   pod 'IGListKit'
end
